// AUTO‑GENERATED by update‑schema.mjs. Do not edit by hand.

import * as AuthenticationSchema from "@/models/drizzle/authentication.model";
import * as EmailSchema from "@/models/drizzle/email.model";
import * as EmailTemplateSchema from "@/models/drizzle/emailTemplate.model";
import * as MediaSchema from "@/models/drizzle/media.model";

const schema = {
	...AuthenticationSchema,
	...EmailSchema,
	...EmailTemplateSchema,
	...MediaSchema
};

export default schema;
